# numpy.loadtxt 用法 读取txt文件

###  numpy.loadtxt(fname, dtype=, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0)  
###  上面给出了loadtxt所有的关键字参数, 这里我们可以来一一解释并给出示例

In [10]:
import numpy as np

In [11]:
# 首先给出最简单的loadtxt的代码,实际上就是直接写文件名, 其他关键字参数都是默认的.
a = np.loadtxt('./data/test.txt')
print(a)  # a为浮点数的原因为Python默认的数字的数据类型为双精度浮点数

[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 3.  4.  5.  6.]
 [ 4.  5.  6.  7.]]


In [12]:
# 这里的skiprows是指跳过前1行, 如果设置skiprows=2, 就会跳过前两行,数据类型设置为整形.
a = np.loadtxt('./data/test.txt', skiprows=1, dtype=int)
print(a)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [13]:
# 这里的comment的是指, 如果行的开头为#就会跳过该行
a = np.loadtxt('./data/test1.txt', dtype=int, skiprows=1, comments='#')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# 这里的usecols是指只使用0,2两列, unpack是指会把每一列当成一个向量输出, 而不是合并在一起。
(a, b) = np.loadtxt('./data/test2.txt', dtype=int, skiprows=1, comments='#', delimiter=',', usecols=(0, 2), unpack=True)
print(a, b)

[1 4 7] [3 6 9]


In [15]:
# 最后介绍converters参数, 这个是对数据进行预处理的参数, 我们可以先定义一个函数， 这里的converters是一个字典, 表示第零列使用函数add_one来进行预处理
def add_one(x):
    return int(x)+1  # 注意到这里使用的字符的数据结构

(a, b) = np.loadtxt('./data/test2.txt', dtype=int, skiprows=1, converters={0:add_one}, comments='#', delimiter=',', usecols=(0, 2), unpack=True)
print(a, b)

[2 5 8] [3 6 9]


## 利用savetxt函数将数据存储到文件
### savetxt(fileName,data)    
fileName:保存文件路径和名称   
data:需要保存的数据  

## 利用 loadtxt函数读取csv文件
### np.loadtxt(filepath,delimiter,usecols,unpack)
filepath:加载文件路径  
delimiter:加载文件分隔符  
usecols:加载数据文件中列索引    
unpack:当加载多列数据时是否需要将数据列进行解耦赋值给不同的变量  

In [20]:
data = np.loadtxt('./data/data.csv',delimiter=',',skiprows=1, usecols=(2,3))
print(data)
print(data.shape)

[[  37.8   69.2]
 [  39.3   45.1]
 [  45.9   69.3]
 [  41.3   58.5]
 [  10.8   58.4]
 [  48.9   75. ]
 [  32.8   23.5]
 [  19.6   11.6]
 [   2.1    1. ]
 [   2.6   21.2]
 [   5.8   24.2]
 [  24.     4. ]
 [  35.1   65.9]
 [   7.6    7.2]
 [  32.9   46. ]
 [  47.7   52.9]
 [  36.6  114. ]
 [  39.6   55.8]
 [  20.5   18.3]
 [  23.9   19.1]
 [  27.7   53.4]
 [   5.1   23.5]
 [  15.9   49.6]
 [  16.9   26.2]
 [  12.6   18.3]
 [   3.5   19.5]
 [  29.3   12.6]
 [  16.7   22.9]
 [  27.1   22.9]
 [  16.    40.8]
 [  28.3   43.2]
 [  17.4   38.6]
 [   1.5   30. ]
 [  20.     0.3]
 [   1.4    7.4]
 [   4.1    8.5]
 [  43.8    5. ]
 [  49.4   45.7]
 [  26.7   35.1]
 [  37.7   32. ]
 [  22.3   31.6]
 [  33.4   38.7]
 [  27.7    1.8]
 [   8.4   26.4]
 [  25.7   43.3]
 [  22.5   31.5]
 [   9.9   35.7]
 [  41.5   18.5]
 [  15.8   49.9]
 [  11.7   36.8]
 [   3.1   34.6]
 [   9.6    3.6]
 [  41.7   39.6]
 [  46.2   58.7]
 [  28.8   15.9]
 [  49.4   60. ]
 [  28.1   41.4]
 [  19.2   16.6]
 [  49.6   37.

In [21]:
#当加载csv文件的多列数据时可以使用unpack将加载的数据列进场解耦到不同数组中
data_seven,data_eight = np.loadtxt("./data/data.csv",delimiter=",",skiprows=1, usecols=(2,3),unpack=True)
print("第7列的数据：\n",data_seven.tolist())
print("第8列的数据：\n",data_eight)


第7列的数据：
 [37.8, 39.3, 45.9, 41.3, 10.8, 48.9, 32.8, 19.6, 2.1, 2.6, 5.8, 24.0, 35.1, 7.6, 32.9, 47.7, 36.6, 39.6, 20.5, 23.9, 27.7, 5.1, 15.9, 16.9, 12.6, 3.5, 29.3, 16.7, 27.1, 16.0, 28.3, 17.4, 1.5, 20.0, 1.4, 4.1, 43.8, 49.4, 26.7, 37.7, 22.3, 33.4, 27.7, 8.4, 25.7, 22.5, 9.9, 41.5, 15.8, 11.7, 3.1, 9.6, 41.7, 46.2, 28.8, 49.4, 28.1, 19.2, 49.6, 29.5, 2.0, 42.7, 15.5, 29.6, 42.8, 9.3, 24.6, 14.5, 27.5, 43.9, 30.6, 14.3, 33.0, 5.7, 24.6, 43.7, 1.6, 28.5, 29.9, 7.7, 26.7, 4.1, 20.3, 44.5, 43.0, 18.4, 27.5, 40.6, 25.5, 47.8, 4.9, 1.5, 33.5, 36.5, 14.0, 31.6, 3.5, 21.0, 42.3, 41.7, 4.3, 36.3, 10.1, 17.2, 34.3, 46.4, 11.0, 0.3, 0.4, 26.9, 8.2, 38.0, 15.4, 20.6, 46.8, 35.0, 14.3, 0.8, 36.9, 16.0, 26.8, 21.7, 2.4, 34.6, 32.3, 11.8, 38.9, 0.0, 49.0, 12.0, 39.6, 2.9, 27.2, 33.5, 38.6, 47.0, 39.0, 28.9, 25.9, 43.9, 17.0, 35.4, 33.2, 5.7, 14.8, 1.9, 7.3, 49.0, 40.3, 25.8, 13.9, 8.4, 23.3, 39.7, 21.1, 11.6, 43.5, 1.3, 36.9, 18.4, 18.1, 35.8, 18.1, 36.8, 14.7, 3.4, 37.6, 5.2, 23.6, 10.6, 11.6, 2