# 1.将矩阵转换为列表的函数：numpy.matrix.tolist（）  
## 返回list列表

In [17]:
import numpy as np  

In [18]:
# x = np.matrix(np.arange(12).reshape((3,4)))
# print(x)
x = np.arange(12).reshape((3,4))
print(x)
print(x.tolist())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


# 2.将数组转换为列表的函数：numpy.ndarray.tolist（）
## Notes：（数组能够被重新构造）
## The array may be recreated, a=np.array(a.tolist()).

In [19]:
a = np.array([1, 2])
print(a.tolist())

# 注意这块的细节
a = np.array([[1, 2], [3, 4]])
print(list(a))
print(a.tolist())

[1, 2]
[array([1, 2]), array([3, 4])]
[[1, 2], [3, 4]]


# 3.numpy.mean() 计算矩阵或数组的均值

In [20]:
a = np.array([[1, 2], [3, 4]])  #对所有元素求均值
print(np.mean(a))
print(np.mean(a, axis=0)) #对每一列求均值
print(np.mean(a, axis=1))   #对每一行求均值

2.5
[ 2.  3.]
[ 1.5  3.5]


# 4.numpy.std()计算矩阵或数组的标准差

In [22]:
a = np.array([[1, 2], [3, 4]])  #对所有元素求标准差 
print(np.std(a))
print(np.std(a, axis=0))    #对每一列求标准差
print(np.std(a, axis=1))    #对每一行求标准差

1.11803398875
[ 1.  1.]
[ 0.5  0.5]


# 5.numpy.newaxis为数组增加一个维度

In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 先输入3行2列的数组a
b = a[:,:2] 
print(b)
print(b.shape)  # 当数组的行与列都大于1时，不需增加维度
c = a[:,2] 
print(c)
print(c.shape)  # 可以看到，当数组只有一列时，缺少列的维度
d = a[:,2,np.newaxis]  # np.newaxis实现增加列的维度
print(d)
print(d.shape)  # d的维度成了3行1列（3,1）
e = a[:,2,None]   # None与np.newaxis实现相同的功能
print(e)
print(e.shape)

[[1 2]
 [4 5]
 [7 8]]
(3, 2)
[3 6 9]
(3,)
[[3]
 [6]
 [9]]
(3, 1)
[[3]
 [6]
 [9]]
(3, 1)


# 6.numpy.random.shuffle(index): 打乱数据集（数组）的顺序

In [26]:
index = [i for i in range(10)]
print(index)
np.random.shuffle(index)
print(index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3, 9, 0, 8, 2, 4, 1, 6, 7, 5]


# 7.计算二维数组某一行或某一列的最大值最小值

In [27]:
a = np.arange(15).reshape(5,3)  # 构造一个5行3列的二维数组
print(a)
b = a[:,0].min()  # 取第0列的最小值，其他列同理
print(b)
c = a[0,:].max() # 取第0行的最大值，其他行同理
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
0
2


# 8.向数组中添加列：np.hstack()

In [42]:
n = np.array(np.random.randn(4,2)) 
print(n)

l = np.array([[1,2,3,4],[2,1,3,5]]) 
print(l) 
print(l.shape)

# 可以看到，n是二维的，l是一维的，如果直接调用np.hstack()会出错：维度不同。
# n = np.hstack((n,l))  # ValueError: all the input arrays must have same number of dimensions
#解决方法是将l变为二维
# n = np.hstack((n,l[:,np.newaxis]))   # 注意：在使用np.hstack()时必须用()把变量括起来，因为它只接受一个变量
print(l[:,np.newaxis])
print(l[:,np.newaxis].shape)
# print(n)

[[-1.70710127 -0.77975625]
 [-1.15013864  1.15554201]
 [ 0.9406852  -0.39925409]
 [-0.33826784  0.9925374 ]]
[[1 2 3 4]
 [2 1 3 5]]
(2, 4)
[[[1 2 3 4]]

 [[2 1 3 5]]]
(2, 1, 4)


# 如何按列往一个空列表添加值

In [35]:
n = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66],[111,222,333,444,555,666]])  # 产生一个三行六列容易区分的数组
print(n)
sample = [[]for i in range(3)]  # 产生三行一列的空列表
print(sample)

for i in range(0,6,2):   # 每间隔一列便添加到sample中
    sample = np.hstack((sample,n[:,i,np.newaxis]))  
    print(n[:,i])
    print(n[:,i,np.newaxis])
print(sample)


[[  1   2   3   4   5   6]
 [ 11  22  33  44  55  66]
 [111 222 333 444 555 666]]
[[], [], []]
[  1  11 111]
[[  1]
 [ 11]
 [111]]
[  3  33 333]
[[  3]
 [ 33]
 [333]]
[  5  55 555]
[[  5]
 [ 55]
 [555]]
[[   1.    3.    5.]
 [  11.   33.   55.]
 [ 111.  333.  555.]]
